"""
report_export.py — Generate Markdown analysis reports for download.
"""
from __future__ import annotations
from datetime import datetime
from utils.edi_parser import EDIParseResult


def generate_report(parse_result: EDIParseResult, nova_result: dict) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    errors   = nova_result.get("errors", [])
    warnings = nova_result.get("warnings", [])
    status   = nova_result.get("overall_status", "UNKNOWN")
    summary  = nova_result.get("summary", "")
    fix_sum  = nova_result.get("fix_summary", "")
    payer    = nova_result.get("payer_notes", "")

    status_icon = {"VALID": "✅", "WARNING": "⚠️", "INVALID": "❌"}.get(status, "❓")

    lines = [
        f"# EDIErrorDoctor Analysis Report",
        f"",
        f"**Generated:** {now}  ",
        f"**Transaction Type:** {parse_result.tx_type_detected}  ",
        f"**Status:** {status_icon} {status}  ",
        f"**Segments:** {parse_result.segment_count}  ",
        f"**SNIP Level:** {parse_result.highest_snip_level}  ",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        summary,
        f"",
        f"---",
        f"",
        f"## Errors ({len(errors)} found)",
        f"",
    ]

    if not errors:
        lines.append("_No errors found._")
    else:
        for e in errors:
            lines += [
                f"### {e.get('error_id','ERR')} — `{e.get('segment','')}`",
                f"",
                f"- **SNIP Level:** {e.get('snip_level','?')}",
                f"- **Element:** {e.get('element','')}",
                f"- **Error Code:** `{e.get('error_code','')}`",
                f"- **Message:** {e.get('message','')}",
                f"",
                f"**Explanation:** {e.get('explanation','')}",
                f"",
            ]
            if e.get("original_segment"):
                lines += [
                    f"**Original:**",
                    f"```",
                    e.get("original_segment",""),
                    f"```",
                    f"",
                ]
            if e.get("corrected_segment"):
                lines += [
                    f"**Corrected:**",
                    f"```",
                    e.get("corrected_segment",""),
                    f"```",
                    f"",
                ]
            if e.get("fix_hint"):
                lines.append(f"💡 **Tip:** {e.get('fix_hint')}")
                lines.append("")

    lines += [
        f"---",
        f"",
        f"## Warnings ({len(warnings)} found)",
        f"",
    ]
    if not warnings:
        lines.append("_No warnings._")
    else:
        for w in warnings:
            lines += [
                f"### {w.get('warning_id','WRN')} — `{w.get('segment','')}`",
                f"",
                f"{w.get('explanation','')}",
                f"",
            ]

    if fix_sum:
        lines += [
            f"---",
            f"",
            f"## Fix Plan",
            f"",
            fix_sum,
            f"",
        ]

    if payer:
        lines += [
            f"---",
            f"",
            f"## Payer Notes",
            f"",
            payer,
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"_Report generated by EDIErrorDoctor | Amazon Nova Hackathon 2025_  ",
        f"_All data in this demo is 100% synthetic — no real PHI._",
    ]

    return "\n".join(lines)
